parameters:
    num_registros_pagina: 50        #numero de registros que se muestran por pagina en una paginaciÃ³n
    web_path: "%kernel.root_dir%/../web"
    carpeta.imagenes.producto: imagenesProducto/
    carpeta.imagenes.creatividad: imagenesCreatividad/
    ruta.instrucciones: %web_path%/instrucciones/
    ruta.batch: batch_generados/

